import uuid
import os
from sqlalchemy.orm import Session
from app.db.database import SessionLocal
from app.services.tools.registry import ToolRegistry
# Ensure tools are registered
import app.services.tools.deliverables

def run_smoke_tests():
    from app.models.user import User
    from app.models.workspace import Workspace
    from app.models.agent import Agent
    from app.models.agent_run import AgentRun
    db = SessionLocal()
    
    test_id = str(uuid.uuid4())[:8]
    user = User(username=f"sm_{test_id}", email=f"{test_id}@a.com", password_hash="x", full_name="sm")
    db.add(user)
    db.commit()
    ws = Workspace(name="sm", created_by=user.id)
    db.add(ws)
    db.commit()
    agent = Agent(name="sm", workspace_id=ws.id, created_by=user.id, agent_type="custom", system_prompt="sm")
    db.add(agent)
    db.commit()
    run = AgentRun(agent_id=agent.id, status="running")
    db.add(run)
    db.commit()
    
    ws_id = ws.id
    run_id = run.id
    
    # 1. DOCX
    docx_tool = ToolRegistry.get_tool("create_docx", db=db, workspace_id=ws_id, agent_run_id=run_id)
    docx_res = docx_tool.execute(
        filename="smoke_test_approval",
        data={
            "title": "Industrial Approval Note",
            "blocks": [
                {"type": "heading", "level": 1, "content": "Findings"},
                {"type": "paragraph", "content": "The pump exhibits normal pressure variations."},
                {"type": "table", "rows": [["Component", "Status"], ["Pump A", "OK"], ["Valve B", "OK"]]}
            ],
            "sources": ["inspection_report_2026.pdf (Page 3)"]
        }
    )
    print(f"DOCX Result: {docx_res.output}")
    
    # 2. XLSX
    xlsx_tool = ToolRegistry.get_tool("create_xlsx", db=db, workspace_id=ws_id, agent_run_id=run_id)
    xlsx_res = xlsx_tool.execute(
        filename="smoke_test_findings",
        data={
            "sheets": [
                {
                    "name": "Measurements",
                    "headers": ["Component", "Pressure (PSI)", "Temperature (C)"],
                    "rows": [
                        ["Pump A", 120, 45],
                        ["Valve B", 110, 42]
                    ]
                }
            ],
            "sources": ["Telemetry System"]
        }
    )
    print(f"XLSX Result: {xlsx_res.output}")
    
    # 3. PPTX
    pptx_tool = ToolRegistry.get_tool("create_pptx", db=db, workspace_id=ws_id, agent_run_id=run_id)
    pptx_res = pptx_tool.execute(
        filename="smoke_test_presentation",
        data={
            "title": "Inspection Executive Summary",
            "subtitle": "Generated by Sovereign Agent",
            "slides": [
                {"title": "Key Findings", "bullets": ["All systems normal", "No leaks detected", "Maintenance scheduled for Q4"]}
            ],
            "sources": ["Inspection Report v2"]
        }
    )
    print(f"PPTX Result: {pptx_res.output}")
    
    # 4. CODE
    code_tool = ToolRegistry.get_tool("create_code_artifact", db=db, workspace_id=ws_id, agent_run_id=run_id)
    code_res = code_tool.execute(
        filename="smoke_test_script.py",
        data={
            "code": "def process_telemetry(data):\n    return [d * 1.5 for d in data]\n\nprint(process_telemetry([10, 20, 30]))",
            "language": "python",
            "source": "Agent Calculation Reasoning"
        }
    )
    print(f"CODE Result: {code_res.output}")

    db.close()

if __name__ == "__main__":
    run_smoke_tests()
