"""Add relationships constraints and indexes

Revision ID: 4490f9c37490
Revises: b0adf8c8da65
Create Date: 2026-09-09 16:26:35.666029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4490f9c37490'
down_revision: Union[str, None] = 'b0adf8c8da65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_agent_knowledge_bases_knowledge_base_id', 'agent_knowledge_bases', ['knowledge_base_id'], unique=False)
    op.create_index('ix_agent_tools_tool_id', 'agent_tools', ['tool_id'], unique=False)
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index('ix_model_workers_status', 'model_workers', ['status'], unique=False)



    op.create_check_constraint("check_documents_file_size_positive", "documents", "file_size_bytes >= 0")
    op.create_check_constraint("check_artifacts_file_size_positive", "artifacts", "file_size_bytes >= 0")
    op.create_check_constraint("check_inference_runs_input_tokens_positive", "model_inference_runs", "input_tokens >= 0")
    op.create_check_constraint("check_inference_runs_output_tokens_positive", "model_inference_runs", "output_tokens >= 0")
    op.create_check_constraint("check_inference_runs_latency_ms_positive", "model_inference_runs", "latency_ms >= 0")
    op.create_check_constraint("check_models_context_length_positive", "models", "context_length > 0")
    op.create_check_constraint("check_document_chunks_chunk_index_positive", "document_chunks", "chunk_index >= 0")
    op.create_check_constraint("check_document_chunks_page_number_positive", "document_chunks", "page_number > 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_workers_status', table_name='model_workers')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.drop_index('ix_agent_tools_tool_id', table_name='agent_tools')
    op.drop_index('ix_agent_knowledge_bases_knowledge_base_id', table_name='agent_knowledge_bases')

    op.drop_constraint("check_document_chunks_page_number_positive", "document_chunks", type_="check")
    op.drop_constraint("check_document_chunks_chunk_index_positive", "document_chunks", type_="check")
    op.drop_constraint("check_models_context_length_positive", "models", type_="check")
    op.drop_constraint("check_inference_runs_latency_ms_positive", "model_inference_runs", type_="check")
    op.drop_constraint("check_inference_runs_output_tokens_positive", "model_inference_runs", type_="check")
    op.drop_constraint("check_inference_runs_input_tokens_positive", "model_inference_runs", type_="check")
    op.drop_constraint("check_artifacts_file_size_positive", "artifacts", type_="check")
    op.drop_constraint("check_documents_file_size_positive", "documents", type_="check")
    # ### end Alembic commands ###
